name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-latest:
    runs-on: ubuntu-24.04
    name: Ubuntu 24.04
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     # Runs a set of commands using the runners shell
     - name: Start build
       run: |
          echo Beginning build
          pwd
          ls -la
          sudo apt-get update
          sudo apt-get install -y git wget automake pkg-config libtool m4 build-essential libncurses-dev
          cd ..
          git clone https://github.com/InterLinked1/lbbs.git
          cd lbbs
          sudo scripts/libetpan.sh
          cd ../evergreen
          make
          sudo make install
  debian-stable:
    runs-on: ubuntu-latest
    name: Debian 12
    container: debian:12
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Start build
       run: |
          apt-get update
          apt-get install -y git wget automake pkg-config libtool m4 build-essential libncurses-dev
          cd ..
          git clone https://github.com/InterLinked1/lbbs.git
          cd lbbs
          scripts/libetpan.sh
          cd ../evergreen
          make
          make install
  debian-11:
    runs-on: ubuntu-latest
    name: Debian 11
    container: debian:11
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Start build
       run: |
          apt-get update
          apt-get install -y git wget automake pkg-config libtool m4 build-essential libncurses-dev
          cd ..
          git clone https://github.com/InterLinked1/lbbs.git
          cd lbbs
          scripts/libetpan.sh
          cd ../evergreen
          make
          make install
  debian-10:
    runs-on: ubuntu-latest
    name: Debian 10
    container: debian:10
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Start build
       run: |
          apt-get update
          apt-get install -y git wget automake pkg-config libtool m4 build-essential libncurses-dev
          cd ..
          git clone https://github.com/InterLinked1/lbbs.git
          cd lbbs
          scripts/libetpan.sh
          cd ../evergreen
          make
          make install
  alpine-linux:
    runs-on: ubuntu-latest
    name: Alpine Linux
    container: alpine:latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Start build
       run: |
          apk update
          apk add git gcc make autoconf automake pkgconf libtool m4 build-base ncurses-dev
          cd ..
          git clone https://github.com/InterLinked1/lbbs.git
          cd lbbs
          mkdir /usr/local/src
          scripts/libetpan.sh
          cd ../evergreen
          make
          make install
  archlinux:
    runs-on: ubuntu-24.04
    name: Arch Linux
    container: archlinux:latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Start build
       run: |
          pacman -Syu --noconfirm
          pacman -Sy --noconfirm git make patch gawk gcc pkg-config autoconf automake m4 libtool libnewt wget
          cd ..
          git clone https://github.com/InterLinked1/lbbs.git
          cd lbbs
          scripts/libetpan.sh
          cd ../evergreen
          make
          make install
  freebsd-14:
    runs-on: ubuntu-24.04
    name: FreeBSD
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          run: |
            pkg install -y git gcc gmake autoconf automake pkgconf libtool m4 ncurses wget
            cd ..
            git clone https://github.com/InterLinked1/lbbs.git
            cd lbbs
            mkdir /usr/local/src
            scripts/libetpan.sh
            cd ../evergreen
            gmake
            gmake install
